name: sanity
on:
  pull_request: {}

jobs:
  sanity:
    name: sanity
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: sudo rm -rf /usr/local/bin/kustomize
    - run: make test-sanity
