name: unit
on:
  pull_request: {}

jobs:
  unit:
    name: unit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make test-unit
